export const FETCH_LINKTREES = "FETCH_LINKTREES";
export const CREATE_LINKTREE = "CREATE_LINKTREE";
export const FETCH_SINGLE_LINKTREE = "FETCH_SINGLE_LINKTREE";
export const DELETE_LINKTREE = "DELETE_LINKTREE";
export const UPDATE_LINKTREE = "UPDATE_LINKTREE";
export const ADMIN_LOGIN = "ADMIN_LOGIN"; 
export const ADMIN_LOGOUT = "ADMIN_LOGOUT"; 